CHANGELOG.md, example/ios/example.xcodeproj/project.pbxproj, ios/RNDateTimePicker.m, ios/RNDateTimePickerManager.m
- iOS React imports fixed
- iOS example project cleaned
- CHANGELOG.md entry will be added once https://github.com/react-native-community/react-native-datetimepicker/pull/3 gets merged
=> Fixing iOS React import and cleaning iOS example project

src/index.d.ts, src/types.js
The `countdown` mode is a valid iOS mode, but the string is not recognized as a valid option by Typescript, and should be added to the type.
To avoid throwing an error, I currently need to use something like `mode={'countdown' as any}`. This is not the intended flow.
Fixes #28 
=> Add `countdown` option to iOSMode types

README.md
I was struggling with installing the lib manually, so I've tried this method. Only after that I've noticed that there's a missing documentation link here, so I decided to add it.
=> add (back?) Install using react-native link section to README

.npmignore
no need to include images and example app in the distributed package. Unpacked size went from 1.27 MB to 87 kB.
=> improve npmignore

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java
I got it from https://gist.github.com/jeffdgr8/6bc5f990bf0c13a7334ce385d482af9f and
did some adjustments in order to work with DatePicker. Workaround for this bug: https://code.google.com/p/android/issues/detail?id=222208. In Android 7.0 Nougat, spinner mode for the DatePicker in DatePickerDialog is incorrectly displayed as calendar.
Run Example with Android Emulator with Android Nougat (7.0), and modify example setting `mode="spinner"`
Run Example in current `master branch` with Android Emulator with Android Nougat (7.0), and modify example setting `mode="spinner"` the emulator shows calendar
=> Fix Android Nougat datetime picker mode="spinner"

.prettierrc, example/App.js, example/e2e/detoxTest.spec.js, jest.config.js, package-lock.json, package.json, src/index.js, test/constants.test.js, test/index.test.js, test/utils.test.js
motivation: actually apply prettier rules
current pipeline passes
=> fix prettier usage

RNDateTimePicker.podspec, example/ios/Podfile, example/ios/Podfile.lock
When running `pod install` get the `pods` from `specific` tag of released version
Go to `example/ios` folder and make `pod install`  open `example project in Xcode` and the example works without problems
| Android     |    ✅❌     |
=> Fix podspec to get source from tag

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
=> fix missing return

src/datetimepicker.js, src/index.js
When using this plugin in a project which targets an environment other than Android or iOS it can't be compiled because the file `datetimepicker` has no default entry.
```
npm install --save git+https://github.com/aikewoody/react-native-datetimepicker.git#feature-support-all-platforms
expo install react-native-web react-dom
expo start --web
```
An Expo project with the `react-native-community/react-native-datetimepicker` plugin installed.
```
npm install --save @react-native-community/datetimepicker@latest
expo install react-native-web react-dom
expo start --web
```
The following error appears:
```
web  Failed to compile.
/Users/.../node_modules/@react-native-community/datetimepicker/src/index.js
Module not found: Can't resolve './datetimepicker' in …
```
=> Support compiling with other platforms

CHANGELOG.md, src/datetimepicker.android.js
After a time value is chosen in the android picker, use the value prop to create the date object so it doesn't default to returning the current date when using the time picker. Closes #94
A test project for android with a time picker set to ```mode="time"```
Pass the time picker a date that is not today, log the value returned from the picker after selecting a time, and see that it returns today's date.
=> Fix android time picker returning today's date instead of the given date

README.md, example/App.js, package.json, src/datetimepicker.ios.js, src/types.js, test/__snapshots__/index.test.js.snap, test/index.test.js
At the moment on iOS picker has fixed height of 216px, this PR exposes a new style property which is passed down to picker itself (style property is only propagated to internal View container and picker can overflow it)
If this style is not defined, we will fall back to height of 216px so it won't break existing apps.
| iOS     |    ✅     	|
| Android |    ❌     	|
=> Add styling prop for iOS picker

CONTRIBUTING.md, RNDateTimePicker.podspec, example/android/app/build.gradle, example/android/settings.gradle, package.json, react-native.config.js
I'd like to rename this repo from `react-native-community/react-native-datetimepicker` to just `react-native-community/datetimepicker` (many other repos follow this convention) and this PR contains some changes to get ready for it. Once it is approved, I'll merged and rename. Github will redirect old links to the new address.
I just did some small changes to android code in example folder; I verified that it runs okay.
=> get repo ready to be renamed to datetimepicker

README.md, example/App.js, example/ios/Podfile.lock, ios/RNDateTimePickerManager.m, src/datetimepicker.ios.js, src/index.d.ts, src/types.js
Add textColor props for iOS datetimepicker (Solves the iOS part of #20)
N/A
N/A
| Android |    N/A     |
=> Add textColor props for iOS datetimepicker

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java, example/App.js
Display spinner should respect `display prop`
Closes #117 
Run this `demo` https://github.com/otaviogaiao/teste-datepicker and `date picker` with mode `spinner` and date picker with spinner should be displayed
=> Fix android nougat display spinner

src/constants.js, src/datetimepicker.android.js, src/types.js, test/index.test.js
closes #135 
motivation: android supports different `display` and `mode` props, but not all combinations are possible, eg you cannot pick a time (mode=time) from a calendar (display=calendar).
This will ensure that in such cases we throw an understandable error from JS.
unit tests were added, tested on device
=> throw when invalid props are passed to android picker

package.json
Reflect recent addition of Windows support in module's keyword set - visible in the npm registry.
=> Add Windows as module keyword in package.json

src/index.d.ts
In the React Native `0.62` the `NativeComponent` was removed and `NativeMethodsMixinStatic` that `NativeComponent const refer` was renamed to `NativeMethods` see this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43179/files#diff-054a3bd6f6ba9a4f60119c781c2a63f6)
Closes #195 
1. git clone https://github.com/salockhart/RNDatePickerError
3. cd DatePickerError
4. `npm install` or `yarn git://github.com/react-native-community/datetimepicker.git#752213fb31c647ae78abbd850a0ec368c715689d`
5. Run tsc
**There should not be TS errors**
=> Change typescript types according the RN 0.62 types on DefinitelyTyped

.circleci/config.yml, .releaserc, package.json, yarn.lock
motivation: we want automatically generated changelogs, and releases.
When this is done, the PRs merged by maintainers need to follow conventions from https://www.conventionalcommits.org/en/v1.0.0/
this _should_ work, I guess:
it can still go wrong in the npm step but I guess we should be good
```
vojta in ~/_dev/_own/datetimepicker 🎁 master [$]$ NPM_TOKEN=abc GH_TOKEN=xyz npx semantic-release --dry-run --ci
[12:17:55 AM] [semantic-release] › ℹ  Running semantic-release version 17.1.1
[12:17:55 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[12:17:55 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[12:17:55 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from …
```
=> chore: add semantic-relase

CHANGELOG.md, ios/RNDateTimePicker.m
Keeps values sent to JS side from resetting the native picker component on iOS.
fixes #192
It's a simple diff check on the Class' `setDate:` method
See issue above
See issue above
Let me know if any other info/changes are needed :)
=> fix time picker sometimes resets to previous value

example/App.js, package.json, yarn.lock
@rectified95 added Windows support to datetime-picker a while back. react-native-windows was added as a peer dependency, but this created warnings in cases where react-native-windows wasn't present in the host app. These warnings are currently present for all community modules with Windows support when RNW isn't installed.
A [follow-up change a few months ago](https://github.com/react-native-community/datetimepicker/commit/feda1770a48489a90f8a9dab73b82ade1c4be468) moved react-native-windows from a peerDependency to an optional dependency. This got rid of the warning but also means that:
- Every user of datetimepicker is now pulling in react-native-windows by default, even if they don't need it
- Due to how it's declared, we now have a transitive peer dependency forcing usage of RN 0.62 …
=> Fix React Native Windows Dependency and Example

RNDateTimePicker.podspec
Xcode 12 won't build if a module depends on React instead of React-Core. 
Reference: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.
=> fix: xcode 12 compatibility

windows/DateTimePickerWindows/DateTimePickerWindows.vcxproj
Fix error produced when module is added to a React Native app and run in Windows emulator.
Error reads: "The target "Deploy" does not exist in the project".
Create a React Native Windows app.
Add datetimepicker module to app via `yarn add`.
Run `npx react-native run-windows`.
If app deploys successfully and loads in the Windows emulator, the code change has succeeded. 
A React Native Windows app. See [here](https://microsoft.github.io/react-native-windows/docs/getting-started) for setup instructions. 
To reproduce error, run steps under "Test Plan" with old version of the module. 
| iOS     |    ✅  |
| Android |    ✅  |
| Windows |    ✅  |
- [X ] I have tested this on a device and a simulator
=> Resolve Missing Deploy Target in Windows

android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java, example/App.js, example/e2e/detoxTest.spec.js, example/e2e/utils/matchers.js, example/e2e/utils/utils.js, src/datepicker.android.js, src/datetimepicker.android.js, src/timepicker.android.js
this replaces #326 because the author did not allow to push into his branch
I figured it was easier to do this separately than by reviews
original description:
> This commit makes the behavior of the android datetimepickers more in
line with other controlled components in react, where unmounting the
component actually dismisses the ui widget as well.
I also think it might be useful to have a way to dismiss android dialogs from JS and this will expose that possibility. The api will be documented later after we change the api of the android picker to an imperative one, as outlined in https://github.com/react-native-datetimepicker/datetimepicker/pull/327#issuecomment-723160992
run demo app, click the "Show and dismiss picker!" button
| iOS …
=> fix: dismiss android datepicker dialog upon unmount

.github/FUNDING.yml
I have finally managed to set up GH sponsors for this organization (which included a bugfix from the sponsors team, so if you tried this before and it didn't work, now it might! 😄 ). It is done through opencollective but makes sponsoring more accessible to folks who have GH but don't want to create an account at opencollective.
=> chore: add GH sponsors for organization

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java
What issues does the pull request solve?
This issue solves the error thrown in Android as follows:
`E/unknown:ReactNative: CatalystInstanceImpl caught native exception
java.lang.IllegalStateException: Method addObserver must be called on the main thread
at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
at androidx.fragment.app.Fragment.initLifecycle(Fragment.java:496)
at androidx.fragment.app.Fragment.<init>(Fragment.java:476)
at androidx.fragment.app.DialogFragment.<init>(DialogFragment.java:138)
at com.reactcommunity.rndatetimepicker.RNDatePickerDialogFragment.<init>(RNDatePickerDialogFragment.java:30)
at com.reactcommunity.rndatetimepicker.RNDatePickerDialogModule. …
=> Lifecycle addObserver crash fix | Android

src/index.d.ts
When building a typescript app that uses a DateTimePicker and running for Windows, typescript checks via `yarn tsc` fail for DateTimePicker props that are specific to Windows (i.e. dayOfWeekFormat, firstDayOfWeek, etc.). index.d.ts was missing type information for Windows Native Props. 
To see issue add DateTimePicker to a typescript React Native Windows app. Add instance of DateTimePicker to App.js which uses a Windows only prop such as dayOfWeekFormat. Run `yarn tsc`. Error will show that 'dayOfWeekFormat' is not valid. 
To show issue is resolved replace old index.d.ts with new in DateTimePicker dir inside of app's node_modules folder. Run `yarn tsc` again and see check run clean. Then run app via `npx react-native run-windows` to show that component continues to render correctly …
=> Add Windows Native Props Types

example/App.js, example/e2e/detoxTest.spec.js
there is an android e2e test that is flaky, this should help albeit not nice
android e2e tests pass repeatedly
=> chore: wait to avoid e2e android flakiness

RNDateTimePicker.podspec
When running a build on the command line, I get the following warning:
```
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'RNDateTimePicker' from project 'Pods')
```
Since the recent iOS minimum for React Native is 9.0, I updated the .podspec to match it.
1. Updated the podspec in my application's `node_modules` folder.
2. Ran an Xcode build.
3. Verified no warnings about `IPHONEOS_DEPLOYMENT_TARGET`
N/A
N/A
| Android |    N/A     |
=> Bump minimum OS version to match Xcode support

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java
Our app crashed with the following call stack:
```
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
at java.util.HashMap$ValueIterator.next(HashMap.java:879)
at androidx.fragment.app.FragmentStore.findFragmentByTag(FragmentStore.java:233)
at androidx.fragment.app.FragmentManager.findFragmentByTag(FragmentManager.java:1677)
at com.reactcommunity.rndatetimepicker.RNTimePickerDialogModule.open(RNTimePickerDialogModule.java:99)
at java.lang.reflect.Method.invoke(Method.java:-2)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java:-2)
at …
```
=> Move all fragment work to UI thread

src/datetimepicker.android.js
replacement for #327, please see motivation there. To sum it up, android dialog's selected date is controlled from JS and while the dialog is open, it will update only if the date changed in JS
Closes #182
Closes #235
Closes #327
tested locally
=> fix: do not update android dialog on each re-render

CONTRIBUTING.md, README.md
This just makes the contribution docs a little more understandable I hope
=> chore: update contrbuting docs

example/App.js, example/e2e/detoxTest.spec.js, example/ios/Podfile.lock, package.json, react-native.config.js
this fixes the ios run script `yarn start:ios` which would previously fail with an error
`start:android` and `start:ios` yarn scripts work
=> chore: fix ios run script

README.md, android/src/main/java/com/reactcommunity/rndatetimepicker/RNConstants.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDate.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java, example/App.js, example/e2e/detoxTest.spec.js, src/constants.js, src/datetimepicker.android.js, src/types.js
=> add Android timezone offset support 

README.md, example/App.js, ios/RNDateTimePickerManager.m, src/datetimepicker.ios.js, src/index.d.ts, src/types.js, test/__snapshots__/index.test.js.snap
Adds ability to disable this control on iOS.
ref #303
Added ability to toggle to example app
=> add disabled support for iOS

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java
Clean PR
#411
This fixes the issue for me. It shows spinner on time. I think when Build.VERSION_CODES.N came it it made sense to use ==, but now there are a ton of newer versions.
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && display == RNDatePickerDisplay.SPINNER) {`
=> Fix for RN Spinner not working right on newer Android devices

example/e2e/detoxTest.spec.js
The `android.widget.DatePicker` is disappearing from the screen after 3 seconds and the e2e tests are failing
e2e tests are running ok
=> fix android e2e test

src/datetimepicker.android.js
There was a change in v3.4.0 (https://github.com/react-native-datetimepicker/datetimepicker/pull/407) that inadvertently caused the time to be set to 0:00 whenever the date is set on Android.
Tested in my app using patch-package.
Applying this patch restores the pre-v3.4.0 behaviour where the time is preserved when the date is changed on Android, making it consistent once again with iOS.
=> Fix time being reset to 0:00 when date changes on Android

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java
Reverts react-native-datetimepicker/datetimepicker#418
=> fix: Revert "Fix for RN Spinner not working right on newer Android devices"

android/src/main/res/values/styles.xml
Resolves #411.
Closes #258
Changes tested in the sample repo (https://github.com/klandell/time-spinner-bug)  in both the main and rn-64 branches on a physical Android device.
=> Remove dependency on upstream RN styles for SpinnerTimePickerDialog and SpinnerTimePickerStyle

android/src/main/java/com/reactcommunity/rndatetimepicker/MinuteIntervalSnappableTimePickerDialog.java
This fixes https://github.com/react-native-datetimepicker/datetimepicker/issues/329.
All changes were made in the file `MinuteIntervalSnappableTimePickerDialog.java`.
When minuteInterval was set on Huawei devices running android 7.0, a ClassCasteException was thrown, causing the app to crash. 
I surrounded the crashing code in `try...catch` and added logging for this specific error. 
Devices running android M and above now no longer use the deprecated functions `setCurrentHour();` and `setCurrentMinute();`.
tested this on 
* Samsung Galaxy S10 
* android 7.0 emulator
* android 11.0 emulator
To test/find the bug, a Huawei device running android 7.0 is needed.
To test the new implementation, any android will do. 
use the datetimepicker with a minuteInterval set. 
| …
=> fix: classCastException on Huawei devices with android 7.0 (#329)

android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java
this is a follow up on https://github.com/react-native-datetimepicker/datetimepicker/pull/424
instead of getting styles by name, we're getting them directly by id
tested manually on device
=> chore: refer to android styles directly by ID

src/timepicker.android.js
fixes #432
tested manually with example app
=> fix: dismiss android time picker on unmount

android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java
Reverts react-native-datetimepicker/datetimepicker#435 which was done prematurely
Closes #437
=> Revert "chore: refer to android styles directly by ID"

ios/RNDateTimePicker.m
* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged
The aim of this PR is to fix an issue that has been previously reported here: https://github.com/react-native-datetimepicker/datetimepicker/issues/192
After the last fix this may still happen. The picker gets back to the previously selected value if the user changes the picker very quickly. This happens specially on slow devices. I had to use an iPad Mini 2 for being able to reproduce it.
The problem seems to appear when the `setDate` is called again through the bridge after the callback was called in the native side of the things. (Native Event -> Native callback -> bridge -> RN rerender -> RN setsDate -> bridge -> Native setDate).
If before the Native setDate is …
=> Do not animate set date

.circleci/config.yml
Ignore node version on yarn install
=> Ignore node version on yarn install

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDate.java, example/e2e/detoxTest.spec.js, src/datetimepicker.android.js
I found out that the datetime picker uses the device timezone by default and if we use the prop `timezoneOffsetInMinutes` then it uses the utc time. Basically the prop `timezoneOffsetInMinutes` was not working. There was already a PR for this fix but it was failing e2e tests and the submitter was not responding since April 10 so I am making this PR in which I have fixed the issue and the e2e tests as well. The PR already made is mentioned below.
https://github.com/react-native-datetimepicker/datetimepicker/pull/431
- (timezones: `device: GMT +3`, `app: GMT -7`)
- pass `2021-04-09T17:00:00.000Z` date (for UTC it stands for `17:00`, but for app timezone `-7` it should be treated like `10:00`)
- pass `timeZoneOffsetInMinutes={-420}` prop (`-420 = -7 * 60`)
- **Expected**: TimePicker should …
=> Fixed Android timezone issues and corresponding e2e test

README.md, ios/RNDateTimePickerManager.m, src/datetimepicker.ios.js, src/index.d.ts, src/types.js
The module allowed overriding locale on ios, but doing so does not really work in newer ios versions. Supporting locales in your app should be done the "proper way" as seen here https://developer.apple.com/documentation/xcode/adding-support-for-languages-and-regions
this is also documented in readme
closes #522, #82, #233, #272, #300, #330, #388, #429, #439
tested locally
=> feat: remove locale prop

README.md, RNDateTimePicker.podspec, example/App.js, example/e2e/detoxTest.spec.js, example/ios/Podfile, example/ios/Podfile.lock, example/ios/example.xcodeproj/project.pbxproj, example/ios/example/AppDelegate.m, package.json, patches/react-native+0.66.4.patch, src/DateTimePickerAndroid.js, src/androidUtils.js, src/constants.js, src/datetimepicker.android.js, src/datetimepicker.ios.js, src/datetimepicker.windows.js, src/index.d.ts, src/index.js, src/types.js, src/utils.js, test/index.test.js, yarn.lock
On Android, this gives a choice between using the component API (regular React component) or an imperative api (think something like ReactNative.alert()).
The component API has the benefit of writing the same code on all platforms, but on Android, the date/time picker opens in a dialog, similar to ReactNative.alert() from core react native. The imperative api models this behavior better than the declarative component api. While the component approach is perfectly functional, based on the issue tracker history, it appears to be more prone to introducing bugs.
The component api internally uses the newly added imperative one, and so the e2e tests which are written using the component api also cover the new imperative one
| iOS     |     ❌ …
=> feat: implement imperative api for android picker

package.json
postinstall is meant only for the example, not the package itself
=> fix: remove wrong postinstall

windows/DateTimePickerWindows.sln, windows/DateTimePickerWindows/DateTimePickerWindows.vcxproj
Fix Windows project so that is compatible with PackageReference usage in RNW v0.68. 
Also updated solution file to include correct projects for dev dep of RNW v0.66.
closes #529 #499
Windows project builds successfully
Covers Windows
=> Fix Windows Project for RNW v0.68

.circleci/config.yml, CONTRIBUTING.md, README.md, example/App.js, example/e2e/utils/matchers.js, ios/RNDateTimePickerManager.m, package.json, src/datetimepicker.ios.js, src/index.d.ts, src/types.js
This adds prop accentColor for iOS.
This relates to #20.
Testing can be done with the example app. I added another input (accentColor) which can be used for testing.
Select display to compact or inline.
Enter a color value (i.e. `#f00`) into the `accentColor` field.
Check if picker appearance changes.
e2e test can not check color changes.
=> Add accentColor props for iOS datetimepicker (#20)

src/picker.windows.js
Changes in #574 break Windows JS because no picker.windows.js file exists.
Tested via React Native Windows app React Native Gallery.
| Windows |    ✅    |
=> Fix Break in Windows JS following #574

README.md, android/src/main/java/com/reactcommunity/rndatetimepicker/RNConstants.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java, src/DateTimePickerAndroid.android.js, src/androidUtils.js, src/datetimepicker.android.js, src/index.d.ts, src/types.js
Android: add custom label for positive and negative button (positiveButtonLabel, negativeButtonLabel)
Allow user to customise android label text for positive and negative button 
via param: positiveButtonLabel, negativeButtonLabel
=> Android: add custom label for positive and negative button 

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java
fix https://github.com/react-native-datetimepicker/datetimepicker/issues/481
this PR will hide the calendar view when spinner mode is selected
only Android is affected, by merging this the spinner date picker on tablets will have the same looks as phones (without calendar view)
=> hide calendar view on Android tablets when the spinner mode is selected

src/DateTimePickerAndroid.android.js, src/index.d.ts
On the native side, the android `dismiss` call returns a promise that the JS side does not return to the call site. 
This fixes that.
tested locally
=> feat: return result of android dialog dismissal

android/src/main/java/com/reactcommunity/rndatetimepicker/MinuteIntervalSnappableTimePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java, example/App.js
closes #606 
as an alternative we can disable the input using `time /date picker .setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS)`
tested manually using example app
=> fix(android): time picker spinner to consider keyboard input

README.md, example/App.js, example/e2e/detoxTest.spec.js, example/ios/Podfile, example/ios/Podfile.lock, ios/RNDateTimePicker.m, ios/RNDateTimePickerManager.m, ios/fabric/RNDateTimePickerComponentView.mm, package.json, src/constants.js, src/datetimepicker.android.js, src/datetimepicker.ios.js, src/index.d.ts, src/specs/DateTimePickerNativeComponent.js, src/types.js, test/__snapshots__/index.test.js.snap, yarn.lock
closes #667
e2e tests cover this
=> feat(ios): dismiss detection support

android/src/main/java/com/reactcommunity/rndatetimepicker/MinuteIntervalSnappableTimePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java, android/src/main/res/values/styles.xml, example/App.js
closes #543
tested locally, see screenshots. Also CI should pass
changing button text color would be nice, that can be done in a separate PR
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
| iOS     |     ❌     |
=> fix(android): spinner buttons invisible

README.md, android/src/main/res/values-night/styles.xml, android/src/main/res/values/styles.xml
follow up on #673 which increases the button text contrast in dark mode
<details>
<summary>screenshot</summary>
</details>
=> fix(android): improve spinner buttons contrast

android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java, android/src/main/java/com/reactcommunity/rndatetimepicker/MinuteIntervalSnappableTimePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDisplay.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDisplay.java, android/src/main/res/values-night/styles.xml, android/src/main/res/values/styles.xml, src/DateTimePickerAndroid.android.js, src/constants.js
closes #678, closes #543
also internally removes the `clock` and `calendar` modes because the `default` mode always (as far as I have seen) resolves to clock / calendar so having `default` and `spinner` is enough. I didn't remove them from the public api in case there's some issue, and also it'd be a breaking change.
Removing them simplifies code and also should fix #543 
tested extensively locally
=> fix(android): bring back parent Dialog theme

.editorconfig, README.md, android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java, src/constants.js, src/datetimepicker.ios.js
This is a follow-up on #680 where I overrode the button text color for all types of pickers, where the intention was to override it only for spinner pickers which suffered from button text not visible.
When someone styles their pickers from xml, that would break the styling, and this should fix it..
also closes #684
The PR also brings in some other code simplifications and improvements.
tested locally
| iOS     |     ❌     |
=> fix: only apply button text color fix to spinner

README.md, android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNConstants.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java, example/App.js, example/android/build.gradle, src/DateTimePickerAndroid.android.js, src/androidUtils.js, src/datetimepicker.android.js, src/index.d.ts, src/types.js
follow up on https://github.com/react-native-datetimepicker/datetimepicker/pull/680 this PR allows setting button color dynamically from JS - android only
tested locally 
=> feat: android dialog buttons text color

README.md, src/datetimepicker.ios.js, src/index.d.ts, src/types.js
this adds support for `onLayout` and potentially other props which previously were not passed to the native component on ios.
tested locally
=> feat: support passing view props

android/src/main/java/com/reactcommunity/rndatetimepicker/KeepDateInRangeListener.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java, example/app.json, example/ios/Podfile.lock
closes #561, but the same issue happens with minimumDate prop.
The issue actually comes from android implementation https://issuetracker.google.com/issues/169602180
tested locally with this change to the example app:
```
const [minimumDate, setMinimumDate] = useState(new Date('2020-12-20'));
const [maximumDate, setMaximumDate] = useState(new Date('2023-01-20'));
```
use the modified example, open android date picker modal, and select year 2020 / 2023 to see that the selected date is within the supplied range
=> fix(android): keep selected date between min and max

windows/DateTimePickerWindows/DateTimePickerWindows.vcxproj
On Windows 11, react-native-windows version 0.68.2 we get a runtime error when trying to use the DateTimePicker after following the manual setup instructions outlined in the repo.
The error occurs when we try to create a new instance of winrt::DateTimePicker::ReactPackageProvider in our App class. The error code is REGDB_E_CLASSNOTREG error, which happens after calling RoGetActivationFactory for the winrt class name DateTimePicker.ReactPackageProvider.
This happens because the winrt class namespace does not match the DLL name. The DateTimePickerWindows project/dll needs to be renamed to just DateTimePicker. 
This PR closes #635 
I have tested this with local modifications to the vcxproj.
With this change, following the manual setup instructions outlined in the repo the date time picker …
=> Renaming the project name from DateTimePickerWindows to DateTimePicker

windows/DateTimePickerWindows/DateTimePickerWindows.vcxproj
On windows 11, DateTimePicker vcxproj defaults the WindowsTargetVersion to 10.0.18382 if no WindowsTargetVersion is specified. We are not able override it with a particular WindowsTargetVersion we are currently using in the parent project (where we use the DateTimePicker as a npm dependency).
This PR solves https://github.com/react-native-datetimepicker/datetimepicker/issues/713
=> Add override props

android/build.gradle
I had some issues when integrating this package elsewhere and this change solves the problem. Moreover, having the ability to control RN version doesn't really serve a purpose here.
e2e tests pass
=> fix: do not use reactNativeVersion in build.gradle

android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java
Summary
The Fix is required in the common.java file.
After installing the following error occurs in android while running the application:
> 
> > Task :react-native-community_datetimepicker:compileDebugJavaWithJavac FAILED
> 168 actionable tasks: 161 executed, 7 up-to-date
> Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
> Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
> Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
> Warning: Mapping new ns …
=> fix error of adding final before context in setButtonTextColor method  in Common.java android

README.md
Expo documentation doesn't mention dev clients: https://docs.expo.dev/versions/latest/sdk/date-time-picker/ You must rebuild your dev client after installing @react-native-community/datetimepicker
=> doc: adds expo dev client instructions

windows/DateTimePickerWindows/DateTimePickerWindows.vcxproj
In RNW .72, we bump WinUI from 2.7 to 2.8 which targets a higher TargetPlatformMinVersion. This PR bumps the WindowsTargetPlatformMinVersion to the correct version for RNW .72
Tested on React Native Gallery
| iOS     |    N/A    |
| Android |    N/A     |
=> fix: windows bump WindowsTargetPlatformMinVersion

README.md, android/src/main/java/com/reactcommunity/rndatetimepicker/DatePickerModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNConstants.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, example/e2e/detoxTest.spec.js, example/e2e/utils/matchers.js, src/DateTimePickerAndroid.android.js, src/androidUtils.js, src/datepicker.android.js, src/datetimepicker.android.js
Makes testID prop work on Android as well.
This makes testing DatePickers with detox easier. Till now this was irrelevant, as detox did not support setting dates on datepickers on Android. 
I am currently working on a PR enabling this very functionality though: https://github.com/wix/Detox/pull/3790
Together with that PR it would be very useful having testID support for DatePickers on Android.
The existing tests are sufficient. I only changed the matchers to not use the android className anymore, but the testID instead. This implicitely tests that the testID is working.
| OS      | Implemented | when |
| ------- | :---------: | ---------------------- |
| iOS     |    ✅      | already implemented before |
| Android |    ✅      | implemented by this PR |
=> Add testID support to android datepicker

android/src/main/java/com/reactcommunity/rndatetimepicker/DatePickerModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/TimePickerModule.java, src/specs/NativeModuleDatePicker.js, src/specs/NativeModuleTimePicker.js
Fixes [767](https://github.com/react-native-datetimepicker/datetimepicker/issues/767) for context. In the past, the android date module was registered under  `RNDatePickerAndroid`. But when this package was updated to support the new arch, the module name was changed to be registered under `RNDatePicker`. The problem is that there is another popular package called [`react-native-date-picker` ](https://github.com/henninghall/react-native-date-picker), which was already registering its android module under `RNDatePicker`. Due to the change mentioned earlier, app that used to depend on both packages now are having a conflict as shown in the linked issue.
This pr basically changes the android module registration names to have an `RNC` prefix to align with other react native community packages …
=> fix: use RNC prefix for android modules

ios/RNDateTimePickerManager.m
After upgrading react native to `0.72.3` the countdown mode stopped working and was fallback to time mode. My guess is that react native changed how `RCT_ENUM_CONVERTER` works.
Adding `countdown` to the enum fixed the issue.
Try passing countdown to mode prop 
| Before | After the fix |
|--------|--------|
| <img width="500px" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/18466484/3ca5928a-21d2-41c6-b5fa-0d6413a243f9" /> | <img width="500px" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/18466484/09b2bac8-4814-44c2-88cf-9b64baa1cb55" /> | 
=> Add missing countdown in RCT_ENUM_CONVERTE

CONTRIBUTING.md
Update the old link inside CONTRIBUTING.md > Detox > Dependencies required.
The link : https://github.com/wix/Detox/blob/master/docs/Introduction.GettingStarted.md#step-1-install-dependencies returns a 404. They changed their docs from the github repo to wix.github.io
a mouse to click on the old link ?
click on the old link -> 404
click on the new link -> get the needed informations to install Detox
=> Fix a broken link inside CONTRIBUTING.md

README.md
Picking dates (especially with Android's device variability) can be tricky and I'd like to be able to test things out on real devices so that I can catch more corner cases and have more confidence in the output. Browserstack can provide that.
=> chore: add real device testing note

RNDateTimePicker.podspec
Split out from #879 , this _just_ updates the podspec without updating the test app and repo to yarn 4. 
CI should pass.
| visionOS     |    ✅      |
=> Add visionOS support in podspec

ios/fabric/cpp/react/renderer/components/RNDateTimePicker/ComponentDescriptors.h
The signature for `ComponentDescriptor::adopt` was changed [here](https://github.com/facebook/react-native/pull/39354). Currently the library will only build on RN 0.72. These changes will not support 0.72 because a pick was missed. I spoke to Riccardo and this will be backported soon
Tested in our (Expos) sample app. The app builds successfully and the library works as expected. 
A RN 0.74 project, new arch, bridgeless.
=> Fix: new arch support for 0.74

README.md
I ran into build issues when installing this via storybook. It was unclear that the latest version of `datetimepicker` was not supported with older versions of react-native. I spent a while figuring this out though other issues and it would be good to include a version support table in the readme so others don't have to figure out backwards compatibility issues
=> Added React Native version support table README.md

README.md, android/src/main/java/com/reactcommunity/rndatetimepicker/DatePickerModule.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNConstants.java, android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java, example/App.js, example/e2e/detoxTest.spec.js, example/e2e/utils/actions.js, example/e2e/utils/matchers.js, src/DateTimePickerAndroid.android.js, src/androidUtils.js, src/datetimepicker.android.js, src/index.d.ts, src/types.js
This feature provides the optional **firstDayOfWeek** functionality to the DatePicker on Android (currently only available in Windows). I was looking for tasks to get started with in the project and I saw this was a pending issue [#196](https://github.com/react-native-datetimepicker/datetimepicker/issues/196), so I decided to implement it.
Although the issue itself is quite old, hopefully it is still useful for someone.
As suggested in the issue thread, https://developer.android.com/reference/android/widget/DatePicker#setFirstDayOfWeek(int) provides the functionality to the Android DatePicker so that is what was used to implement it. The rest was simply bridging the props from React Native component to Android. 
The `firstDayOfWeek` prop accepts the `DAY_OF_WEEK` constant to set the first …
=> feat: Add set first day week android

.circleci/config.yml, .detoxrc.js, example/App.js, example/e2e/detoxTest.spec.js, example/e2e/utils/actions.js
This PR aims to fix the need for tests to contain scrolling to accommodate the recent changes to the example app's App.js file. This stems from a short conversation that took place in #902.
First off I have reverted the test changes done in #902, specifically those that added `scrollTo('bottom')` or `scrollTo('top')`. I then implemented some small styling changes to App.js that reduces the separation between the different inputs on the main screen. Lastly, I changed the test devices to an **iPhone 15 Pro Max** for iOS and a **Pixel 6 Pro** for Android, both of which are larger and provide enough space to show all elements of the test App without scrolling.
*Please note that for Android, we simply state the TestingAVD name in `.detoxrc`, which Im pretty sure does not change the actual test …
=> fix: Tests without scrolling

android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
This is a regression in 8.1.0 caused by the removal of a condition that sets the max date in Android:
https://github.com/react-native-datetimepicker/datetimepicker/commit/3b635633844864cdfd7a109ffe927e271872213e#diff-c69fee0670676f78b9b27aeb6fbadc9c9edf486510166dc8194c5c8232f626ecL119-L121
Run the example app using the command: `yarn start:android`
Tap `TOGGLEMINMAXDATE` button to open the DatePicker dialog. One should only be able to tap the available dates. 
=> fix(android): Re-enable setting max date

android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java
The changes handle the fetching of color resources more accurately in our Common.java file. The old method was simplified to one line, but this didn't consider raw color values. Now, the code correctly handles both cases: when the type value is resolved to a color resource ID, and when it's resolved to a raw color value.
Handling Default Values
If the textColorPrimary attribute is not explicitly defined in your theme, the typedValue.resourceId might still be 0, and typedValue.data might contain a raw color value instead of a resource ID. This could lead to unexpected behavior if you're expecting a resource ID.
Explicit Check: We now explicitly check if typedValue.resourceId is non-zero before assuming it's a resource ID.
Raw Color Handling: If typedValue.resourceId is 0, we directly use …
=> Improve color resource handling in Common.java

android/src/main/java/com/reactcommunity/rndatetimepicker/RNMaterialDatePicker.kt
This PR retrieves the resource ID of the materialCalendarTheme specified by the user inside `styles.xml`, which will default to the material 3 theme if not specified. This enables theming the date picker component when using Material 3 instead of user styling being overridden by the default theme.
Issue: https://github.com/react-native-datetimepicker/datetimepicker/issues/960
=> feat: :sparkles: enables theme overlays for material 3 date pickers

ios/fabric/RNDateTimePickerComponentView.mm
The application crashes when `minuteInterval` is not provided or is 0. The issue was introduced in the previous PR which modified the minimum date check https://github.com/react-native-datetimepicker/datetimepicker/pull/992
Fixes https://github.com/react-native-datetimepicker/datetimepicker/issues/996
- Add the component
- Dont provide minimumDate prop
- The app crashes
=> Fix division by zero minute interval

android/src/main/java/com/reactcommunity/rndatetimepicker/MaterialDatePickerModule.kt, android/src/main/java/com/reactcommunity/rndatetimepicker/MaterialTimePickerModule.kt
=> chore: update current activity for 0.81 version
