react-native-datetimepicker/datetimepicker

- CHANGELOG.md
> [doc] move inline links to bottom of changelog

- README.md
Use markdown for images, [rendered content](https://github.com/react-native-community/react-native-datetimepicker/blob/Swaagie-patch-1/README.md)
~~- [ ] I have tested this on a device and a simulator~~
~~- [ ] I mentioned this change in `CHANGELOG.md`~~
~~- [ ] I updated the typed files (TS and Flow)~~
~~- [ ] I added a sample use of the API in the example project (`example/App.js`)~~
> [doc] update images

- example/App.js
If you run example app you would get the error:
> Unable to resolve module `react-native-datetimepicker`
`cd` into the example folder and try to launch the app.
[Before fix](https://user-images.githubusercontent.com/21033162/60087613-a1829680-973d-11e9-9ae1-68818b796de9.png)
[After fix](https://user-images.githubusercontent.com/21033162/60087852-0f2ec280-973e-11e9-8739-65f873bc66ee.png)
> Fix import/change to new package name

- src/index.d.ts
It mentions https://github.com/react-native-community/react-native-datetimepicker/issues/17
> feat: added typescript definitions

- README.md
> fix closing backtick

- package.json
currently, IDEs can not detect the file definition and so they can't doing type checking and autosuggestion.
> Added type definition file path to package.json

- android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java
- android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java
- android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java
- android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java
- android/src/main/java/com/reactcommunity/rndatetimepicker/ReflectionHelper.java
motivation: remove duplication
ran on android emulator 7 and 10
> remove duplicated findField()

- README.md
- example/App.js
- src/datetimepicker.js
Demo using `function component` with `hooks`
Fix #88
> Update readme and example with function component and hooks

- example/App.js
- example/android/build.gradle
Demonstrate how to use date picker with display spinner
Run Example App on Android Emulator using android 7.1.1 and open date picker with default display and change to date picker with display spinner and everything is working
> Add spinner display mode on example

- README.md
fixed Example code on readme.md so that the example code will not produce picker twice on Android, hence need to be confirmed/canceled twice.
I think this will help more confused people like myself, who copy paste the example code, and find it not working properly.
Area of impact, only in readme.md file.
> Update Readme.md to fix example code

- CHANGELOG.md
- package.json
Changelog update and `package.json` version bump
> Update changelog/ios style property

- src/index.d.ts
Small PR to fix typescript compilation failure.
- [x ] I have tested this on a device and a simulator
> Fixing typescript compilation errors

- package-lock.json
- package.json
Small PR to update eslint-config-react-native-community to v1.0.0
> Update eslint-config to v1.0.0

- CHANGELOG.md
- package.json
- src/index.d.ts
this changes `ColorValue` to `string`, which is not correct but better than `ColorValue` which is a flow type. Also reformats typings with our prettier config.
- lint passes
> fix color type in TS

- README.md
Add Xcode 11 to requirements section because are some issues with build problems that can be fixed updating the Xcode
Closes #133 
> Add Xcode 11 to requirements section

- README.md
> remove timeZoneOffsetInMinutes={0} from example

- README.md
motivation: clarify the default mode meaning
> clarify the default mode meaning

- CHANGELOG.md
- README.md
> fix: fix link in readme

- README.md
> Update Readme intro with Windows info.

- README.md
Fix circle ci status in README
> Fix circle ci status

- README.md
the motivation is to avoid confusion that expo users have around some stuff not working in expo
closes #238
> chore: document usage with expo

- example/App.js
- example/e2e/detoxTest.spec.js
- example/e2e/utils/actions.js
- example/e2e/utils/matchers.js
- example/e2e/utils/utils.js
- example/ios/Podfile.lock
- package.json
closes #198 because it confirms that the prop generally works (it's now covered by a test). new issue should be opened in case the problem can still be reproduced (with repro).
I also did some small refactors and added some helper fns
e2e tests pass
| iOS     |    ✅    |
> chore: refactor e2e tests

- README.md
document Xcode >= 11.6 is required
> chore: document Xcode >= 11.6 is required

- CHANGELOG.md
- README.md
- ios/RNDateTimePickerManager.m
fixes #247
build and test with xcode 11 and 12
| iOS     |    ✅   |
> fix: prevent unrecognized selector setHighlightsToday on iOS 14

- .github/FUNDING.yml
I'm not sure this is going to work but let's give it a try :D
motivation is to have an opencollective account for sponsoring the project, through which we would fund the development and maintenance of the project
> chore: add opencollective link

- README.md
I think this is self-explanatory
> chore: add repo transfer notice and support message

- README.md
fix circle ci status badge according new org
The badge should show the build status from circle ci
> fix circle ci status badge according new org

- README.md
motivation: opened a new issue where potential people who are interested in maintenance can discuss
> chore: add issue about looking for maintainers to docs

- package.json
motivation: the latest versions of this package require RN 0.60 so we should make that clear :)
> chore: correct RN peer dependency version

- .github/label-actions.yml
> chore: update bug report template url

- README.md
> docs: document minuteinterval on ios 14

- .github/label-actions.yml
just updated the comment we use to close issues :)
> chore: update message for closing issues

- README.md
- ios/RNDateTimePickerManager.m
- src/datetimepicker.ios.js
- src/index.d.ts
- src/types.js
For iOS apps that:
- made the decision of a light/dark UI regardless of system preferences
- or allow user to change theme manually in some settings,
the picker is challenging to integrate in spinner+inline modes, since text is likely to be white-on-white or dark-or-dark.
As demonstrated here:
- inline
- spinner
⚠️ this will only work on iOS 13+ due to the use of `setOverrideUserInterfaceStyle`. For iOS 12-, one can only use "spinner" mode, and can use the existing `textColor` to have a convenient UI
Tested on:
- iOS 14.5.1 real device
- iOS 12.4 simulator
In cases:
- prop `themeVariant="light"` and system light
- prop `themeVariant="light"` and system dark
- prop `themeVariant="dark"` and system light
- prop `themeVariant="dark"` and system dark
- prop `themeVariant` unset and system …
> feat: Allow overriding theme variant used by native ios picker

- .circleci/config.yml
- example/App.js
- example/e2e/detoxTest.spec.js
- package.json
- yarn.lock
Fix npm install error and remove unnecessary peer dependencies
Close #441 
> fix: remove unnecessary peer dependencies

- README.md
This just adds a backers banner to readme.
A way to say thanks and perhaps encourage more backers to join :)
> chore: add backers to readme

- .github/label-actions.yml
- .github/workflows/label-actions.yml
> chore: automate issues with labels

- .github/label-actions.yml
> chore: automate issues with labels 2

- README.md
> docs: prefer import to require

- README.md
This should further clarify localization, and there are other small improvements in readme.
> docs: minor readme improvements

- ios/RNDateTimePickerManager.m
Fixes build failure in Xcode 12 #585
Builds in Xcode 12.5 and Xcode 13.3
> UIColor tintColor in Xcode 12

- yarn.lock
Vulnerability explanation https://github.com/advisories/GHSA-gff7-g5r8-mg8m
Run 
```
yarn list --pattern simple-plist
```
it should be the version with the fix `1.3.1`
> fix: update simple-plist to fix security vulnerability

- package.json
closes #640 
ran npm pack and verified the files are present
> fix: distribute jest folder

- README.md
closes #523  
Theme-related stuff was mentioned repeatedly in issues and using this library can help so I'm documenting it.
> docs: document using react-native-theme-control

- .circleci/config.yml
> chore: use node 16 in ci

- src/DateTimePickerAndroid.android.js
> fix: android button labels not working

- ios/RNDateTimePickerShadowView.m
- ios/fabric/RNDateTimePickerComponentView.mm
With [this](https://github.com/react-native-datetimepicker/datetimepicker/pull/656) PR, we've started computing the date picker size via a shadow view, so that the date picker gains intrinsic size.
Using `sizeThatFits:UILayoutFittingCompressedSize` has, however, lead to the date format being changed in some instances (when the date gets longer):
https://screenshot.click/18-46-u9noh-51646.mp4
Notice when the date is changed to 23rd November from 13th November, the value is `11/23/21` instead of `Nov 23, 2021`.
This is because the aforementioned method returns width that allows the longer form only for some dates. Imho, this is a bug in `UIDatePicker` and I couldn't figure out a better way to keep the form most of the time the same than to add a fixed 10 pt to the width. This seems to work …
> Fix date format change

- .circleci/config.yml
just updating the circle ci orbs
> chore: ci updates

- README.md
replacement for https://github.com/react-native-datetimepicker/datetimepicker/pull/730 which somehow didn't release
> feat: release v7

- README.md
- No testing required only readme docs are updated
- Nil
- [✓ ] I added the documentation in `README.md`
> doc: updated the incorrect value for negativeButtonLabel documentation

- package.json
- yarn.lock
> chore: use detox compatible with jest 29

- android/build.gradle
- android/src/main/java/com/reactcommunity/rndatetimepicker/RNDateTimePickerPackage.java
as per https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1597386954
e2e tests pass
> feat: RN 0.73 compatibility

- README.md
- The datetime or time picker should pop up by passing (true) as a value to the setShow() function when the button is pressed.
> Update (README, Doc): Show the datetime/time picker when the button is pressed. 

- ios/RNDateTimePickerShadowView.h
fixes: https://github.com/react-native-datetimepicker/datetimepicker/issues/811
> Fix header import

- patches/detox+20.13.5.patch
> chore: log more in ci

- .circleci/config.yml
> chore: update resource_class: large

- docs/android-styling.md
> docs: fix plugin syntax

- .circleci/config.yml
- README.md
- docs/android-styling.md
> chore: update styling docs

- README.md
> update supported versions
